Fix compatibility issue for dynamic feature
googlesamples/android-instant-apps pull request #56
Opened 2018-08-31 18:39 UTC by IgorGanapolsky

Update versions in build.gradle files.

2018-09-11 10:06 UTC, keyboardsurfer commented
Hi Igor and thanks for this PR. It introduces a lot of files that are not necessary to compile the project and contains a lot of changes. It's hard to find the spot where this actually fixes something.
Before I can evaluate a fix and potentially approve it this needs to be cleaned up.

2018-09-13 10:55 UTC, IgorGanapolsky commented
@keyboardsurfer Do you advise adding **.gitignore** to this project?  That is the reason for so many files...

2018-09-19 08:52 UTC, keyboardsurfer commented
I've got a global .gitignore file which I keep for all projects.
It contains things such as .idea folder and .iml files.

2018-09-19 08:56 UTC, keyboardsurfer requested changes

2018-09-19 08:56 UTC, keyboardsurfer commented on install-api/features/base/build.gradle
> +//    buildToolsVersion rootProject.buildTools
Don't add scar tissue. Remove the commented out lines completely.

2018-09-19 08:56 UTC, keyboardsurfer commented on multi-feature-module/.idea/libraries/Gradle__android_arch_core_common_1_1_0_jar.xml
> +<component name="libraryTable">
Remove .idea folder completely.

2018-09-19 08:56 UTC, keyboardsurfer commented on multi-feature-module/detail/detail.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove .iml files.

2018-09-19 08:56 UTC, keyboardsurfer commented on urlless/.gitignore
> +# built application files
One single .gitignore for the whole project should be enough. Keep it in the project root.

2018-09-19 08:56 UTC, keyboardsurfer commented on urlless/README.md
> +Install Instant Apps Development SDK (revision: 1.2.0) from Android SDK Manager.
Revert

2018-09-19 08:56 UTC, keyboardsurfer commented on urlless/feature/src/main/java/com/google/android/instantapps/samples/urlless/feature/MainActivity.java
This is not necessary within this change.

2018-09-19 08:56 UTC, keyboardsurfer commented on urlless/local.properties
> +## This file must *NOT* be checked into Version Control Systems,
Remove file

2018-09-19 10:45 UTC, IgorGanapolsky commented
I think the main issue is that git forces parent directories to be committed if one is using **.gitignore**.  Fore example, my changes to **urlless** project inherently force changes upon ** multi-feature-module**,  **install-api**, and other project in the parent folder.  That is the way git is designed to work with .gitignore files (AFAIK).  So we have two options:
1) scrap this entire PR and start over
2) figure out a way to break these projects into truly separate repos, so that they don't step on each others' feet.

2018-09-19 10:53 UTC, keyboardsurfer commented
I'm okay with closing this PR and starting over.
AFAIK .gitignore files don't traverse the tree upwards, so I suggest editing the file in the project root.

2018-09-19 10:59 UTC, closed without merging